export type ProjectCategory = "web" | "mobile" | "game" | "3d";

export type Project = {
  id: number;
  cat: ProjectCategory;
  title: string;
  desc: string;
  tags: string[];
  thumb: string;
  gallery: string[];
};

/**
 * Image paths match files under `public/projects/` only (verified on disk).
 * Galleries list every image available per project; many folders currently have a single screenshot.
 */
export const PROJECTS: Project[] = [
  /* WEB */
  {
    id: 1,
    cat: "web",
    title: "JP Culture Day",
    desc: "An immersive cultural web experience celebrating Japanese traditions, festivals and heritage with rich visual storytelling and interactive elements.",
    tags: ["HTML5", "CSS3", "JavaScript", "Animation"],
    thumb: "/projects/Web/JP culture Day/Home.jpg",
    gallery: ["/projects/Web/JP culture Day/Home.jpg"],
  },
  {
    id: 2,
    cat: "web",
    title: "EcoGreen E-Commerce",
    desc: "Sustainable e-commerce platform for eco-friendly products featuring modern checkout, product management, and a clean responsive storefront.",
    tags: ["React", "Node.js", "Stripe", "MongoDB"],
    thumb: "/projects/Web/ecomerce- EcoGreen/Screenshot_1.png",
    gallery: ["/projects/Web/ecomerce- EcoGreen/Screenshot_1.png"],
  },
  {
    id: 3,
    cat: "web",
    title: "Education Platform",
    desc: "Interactive e-learning platform with course management, video lessons, progress tracking, quizzes and certificates.",
    tags: ["Vue.js", "Laravel", "MySQL", "WebRTC"],
    thumb: "/projects/Web/education/Screenshot_1.png",
    gallery: ["/projects/Web/education/Screenshot_1.png"],
  },
  /* GAMES */
  {
    id: 4,
    cat: "game",
    title: "ShadowBorn",
    desc: "Dark atmospheric action game featuring stealth mechanics, shadow manipulation, intense combat, and epic multi-stage boss battles.",
    tags: ["Unity", "C#", "Game Design", "Shader"],
    thumb: "/projects/Game/1-ShadowBorn/1.png",
    gallery: ["/projects/Game/1-ShadowBorn/1.png"],
  },
  {
    id: 5,
    cat: "game",
    title: "Stellar Wanderer",
    desc: "Space exploration adventure with procedural generation, alien civilizations, ship customization and interstellar travel across the galaxy.",
    tags: ["Unity", "C#", "Procedural Gen", "VFX"],
    thumb: "/projects/Game/1-Stellar Wanderer/1.png",
    gallery: ["/projects/Game/1-Stellar Wanderer/1.png"],
  },
  {
    id: 6,
    cat: "game",
    title: "Spark Riders",
    desc: "Fast-paced electrifying racing game with lightning-powered vehicles, dynamic weather tracks, and competitive multiplayer modes.",
    tags: ["Unity", "C#", "Racing", "Multiplayer"],
    thumb: "/projects/Game/1-Spark Riders/1.png",
    gallery: ["/projects/Game/1-Spark Riders/1.png"],
  },
  {
    id: 7,
    cat: "game",
    title: "No Wifi Games Collection",
    desc: "A curated bundle of offline-playable games requiring no internet connection — perfect for commuters and casual gamers anywhere.",
    tags: ["Unity", "C#", "Offline", "Mobile"],
    thumb: "/projects/Game/1-No Wifi Games/1.png",
    gallery: ["/projects/Game/1-No Wifi Games/1.png"],
  },
  {
    id: 8,
    cat: "game",
    title: "Urban Crosser — 3D Web Game",
    desc: "High-quality 3D endless crossing game built with Three.js. Navigate city roads with realistic lighting, animated environments and full mobile touch support.",
    tags: ["Three.js", "JavaScript", "WebGL", "3D"],
    thumb: "/projects/Game/Urban Crosser – 3D Endless Crossing Game/screenshot_1.png",
    gallery: [
      "/projects/Game/Urban Crosser – 3D Endless Crossing Game/screenshot_1.png",
    ],
  },
  {
    id: 9,
    cat: "game",
    title: "Light Bulb Puzzle",
    desc: "Addictive logic puzzle game where tapping one bulb affects connected neighbours. Features increasing difficulty and satisfying chain-reaction animations.",
    tags: ["HTML5", "JavaScript", "Construct 3", "Puzzle"],
    thumb: "/projects/Game/Game- Light Bulb Puzzle/sc1.png",
    gallery: ["/projects/Game/Game- Light Bulb Puzzle/sc1.png"],
  },
  {
    id: 10,
    cat: "game",
    title: "Slot Party — HTML5",
    desc: "Feature-rich HTML5 slot machine game with beautiful graphics, smooth animations and cross-platform support (PC, iOS, Android) built in Construct 3.",
    tags: ["HTML5", "Construct 3", "Canvas", "Casino"],
    thumb: "/projects/Game/Game-Slot Party/2.png",
    gallery: ["/projects/Game/Game-Slot Party/2.png"],
  },
  {
    id: 11,
    cat: "game",
    title: "3D European Roulette",
    desc: "Professional 3D roulette simulation with European and French variants, physically accurate ball physics, real-time chip stacking and betting history.",
    tags: ["Three.js", "JavaScript", "Physics", "3D"],
    thumb: "/projects/Game/3D Roulette (EuropeanFrench Roulette)/screenshot1.png",
    gallery: [
      "/projects/Game/3D Roulette (EuropeanFrench Roulette)/screenshot1.png",
    ],
  },
  {
    id: 12,
    cat: "game",
    title: "Casino Platform — Lime Agency",
    desc: "Full-featured online casino platform with multiple games, smooth lobby transitions, wallet management and responsive cross-device design.",
    tags: ["HTML5", "CSS3", "JavaScript", "Casino"],
    thumb: "/projects/Game/Casino game (Lime Agency)/casino.png",
    gallery: ["/projects/Game/Casino game (Lime Agency)/casino.png"],
  },
  {
    id: 13,
    cat: "game",
    title: "Poker Desktop",
    desc: "Desktop poker game with full Texas Hold'em mechanics, AI opponents of varying difficulty, chip management, and polished UI animations.",
    tags: ["JavaScript", "HTML5", "Game Logic", "AI"],
    thumb: "/projects/Game/Game-Pocker/Desktop1.png",
    gallery: ["/projects/Game/Game-Pocker/Desktop1.png"],
  },
  /* MOBILE */
  {
    id: 14,
    cat: "mobile",
    title: "AI Calorie Counter",
    desc: "AI-powered nutrition tracking app that recognises food from photos using computer vision and instantly calculates calories, macros and meal history.",
    tags: ["Flutter", "TensorFlow", "Firebase", "AI/ML"],
    thumb: "/projects/anroid mobile/AI Calorie Counter/1.png",
    gallery: ["/projects/anroid mobile/AI Calorie Counter/1.png"],
  },
  {
    id: 15,
    cat: "mobile",
    title: "Hotel & Travel Booking",
    desc: "Comprehensive travel app with hotel search, flight booking, trip planner, interactive maps and secure payment integration.",
    tags: ["Flutter", "REST API", "Firebase", "Maps"],
    thumb: "/projects/anroid mobile/Booking Hotels and more/1.png",
    gallery: ["/projects/anroid mobile/Booking Hotels and more/1.png"],
  },
  {
    id: 16,
    cat: "mobile",
    title: "CityMaps2Go",
    desc: "Offline city maps app for travellers featuring downloadable map packs, POI discovery, AR wayfinding and multi-city itinerary planning.",
    tags: ["Android", "Kotlin", "Maps SDK", "Offline"],
    thumb: "/projects/anroid mobile/CityMaps2Go maps/1.png",
    gallery: ["/projects/anroid mobile/CityMaps2Go maps/1.png"],
  },
  {
    id: 17,
    cat: "mobile",
    title: "Fintech News App",
    desc: "Real-time fintech and crypto news aggregator with personalised feeds, market data widgets, push alerts and bookmark management.",
    tags: ["React Native", "REST API", "Push Notifications"],
    thumb: "/projects/anroid mobile/Fintech News/1.png",
    gallery: ["/projects/anroid mobile/Fintech News/1.png"],
  },
  {
    id: 18,
    cat: "mobile",
    title: "Food Delivery App",
    desc: "On-demand food delivery platform with restaurant listings, real-time order tracking, in-app chat with couriers and ratings system.",
    tags: ["Flutter", "Firebase", "Google Maps", "Stripe"],
    thumb: "/projects/anroid mobile/Food deliver/cover.png",
    gallery: ["/projects/anroid mobile/Food deliver/cover.png"],
  },
  {
    id: 19,
    cat: "mobile",
    title: "Global Fintech Fest",
    desc: "Conference app for a major global fintech event — sessions schedule, speaker profiles, networking features, live polls and gamification.",
    tags: ["React Native", "Firebase", "QR Code", "Events"],
    thumb: "/projects/anroid mobile/Global Fintech Fest/1.png",
    gallery: ["/projects/anroid mobile/Global Fintech Fest/1.png"],
  },
  {
    id: 20,
    cat: "mobile",
    title: "Japanese Friends Chat",
    desc: "Language exchange app connecting Japanese learners with native speakers for conversational practice, vocabulary drills and cultural exchange.",
    tags: ["React Native", "Firebase", "WebSocket", "NLP"],
    thumb: "/projects/anroid mobile/Japanese Friends Chat(Education)/cover.png",
    gallery: [
      "/projects/anroid mobile/Japanese Friends Chat(Education)/cover.png",
    ],
  },
  {
    id: 22,
    cat: "mobile",
    title: "Tai Chi & Chair Yoga",
    desc: "Wellness app with guided Tai Chi and Chair Yoga sessions for all ages, daily practice reminders, progress streaks and breathing exercises.",
    tags: ["Flutter", "Video Streaming", "Health", "Firebase"],
    thumb: "/projects/anroid mobile/Tai Chi Walking & Chair Yoga/1.png",
    gallery: ["/projects/anroid mobile/Tai Chi Walking & Chair Yoga/1.png"],
  },
  {
    id: 23,
    cat: "mobile",
    title: "Voice GPS Navigation",
    desc: "Offline-capable GPS navigation with turn-by-turn voice guidance, live traffic overlay, lane assistance and multi-language voice packs.",
    tags: ["Android", "Kotlin", "Maps API", "TTS"],
    thumb: "/projects/anroid mobile/Voice GPS Navigation/1.png",
    gallery: ["/projects/anroid mobile/Voice GPS Navigation/1.png"],
  },
  /* 3D — two assets shared across character vs environment entries */
  {
    id: 24,
    cat: "3d",
    title: "Low-Poly Character Art",
    desc: "Collection of low-poly 3D character models with full UV unwrapping and texture baking, optimised for real-time rendering in games and apps.",
    tags: ["Blender", "3D Modeling", "UV Mapping", "Low-Poly"],
    thumb: "/projects/3Ds/590x590 LowPoly Male_UV_JPG.jpg",
    gallery: ["/projects/3Ds/590x590 LowPoly Male_UV_JPG.jpg"],
  },
  {
    id: 25,
    cat: "3d",
    title: "3D Environment Scenes",
    desc: "Stylised 3D environment and scene compositions — from sci-fi interiors to natural landscapes, built for interactive media and visualisation.",
    tags: ["Blender", "Three.js", "WebGL", "Lighting"],
    thumb: "/projects/3Ds/preview.jpg",
    gallery: ["/projects/3Ds/preview.jpg"],
  },
  /* WEB (additional) */
  {
    id: 26,
    cat: "web",
    title: "Byfood — Food Discovery Japan",
    desc: "Japanese food experience platform connecting travellers with authentic restaurants, food tours and unique dining simulations across Japan. Built with Sass and a modern component-based architecture.",
    tags: ["Sass", "JavaScript", "SaaS", "UX Design"],
    thumb: "/projects/Web/byfood (food healthcare, sass)/1.png",
    gallery: ["/projects/Web/byfood (food healthcare, sass)/1.png"],
  },
  {
    id: 27,
    cat: "web",
    title: "Chaintope — Blockchain Trust",
    desc: "Corporate website for Chaintope, a Japanese blockchain company building trusted data infrastructure for finance and insurance. Clean, modern design with animated data visualisations.",
    tags: ["React", "Blockchain", "Corporate", "Animation"],
    thumb: "/projects/Web/chaintope (insurance)/1.png",
    gallery: ["/projects/Web/chaintope (insurance)/1.png"],
  },
  {
    id: 28,
    cat: "web",
    title: "Zococity — Electronics E-Commerce",
    desc: "Full-featured electronics and hi-fi audio e-commerce platform for the Spanish market. Product catalogue, search filters, cart management and promotional campaign system.",
    tags: ["PHP", "E-Commerce", "CSS3", "JavaScript"],
    thumb: "/projects/Web/zococity/1.png",
    gallery: ["/projects/Web/zococity/1.png"],
  },
  {
    id: 29,
    cat: "web",
    title: "Auto Analyze Resumes — AI CRM",
    desc: "AI-powered CRM dashboard with automated resume analysis, growth intelligence, predictive sales analytics and real-time candidate insights. Sleek dark-mode SaaS interface.",
    tags: ["React", "AI/ML", "SaaS", "Data Viz"],
    thumb: "/projects/Web/auto analyze the resumes.png",
    gallery: ["/projects/Web/auto analyze the resumes.png"],
  },
  {
    id: 30,
    cat: "web",
    title: "ELIA — AI Legal Assistant",
    desc: "AI-powered legal chatbot for EDJ XTech Law School. Helps startups navigate GDPR, EU AI Act, DORA, MiCA and 60+ regulations with instant, confidential AI legal advice.",
    tags: ["AI/ML", "Chatbot", "LangChain", "SaaS"],
    thumb: "/projects/Web/project-elia-DHWOe72d.png",
    gallery: ["/projects/Web/project-elia-DHWOe72d.png"],
  },
];
